openapi: 3.1.0
info:
  title: MLB StatAPI
  license:
    name: "Public Domain"
    identifier: "Public Domain"
  description: >
    An spec API to consume the MLB Stat API
  version: 0.5.0
  contact:
    name: "dave@mudsite.com"

servers:
  - url: https://statsapi.mlb.com/api

tags:
  - name: mlb
    description: MLB API

paths:
  /v1/divisions:
    $ref: ./paths/divisions.yaml
  /v1/game/{gamePk}/boxscore:
    $ref: ./paths/boxscore.yaml
  /v1/game/{gamePk}/linescore:
    $ref: ./paths/linescore.yaml
  /v1/leagues:
    $ref: ./paths/leagues.yaml
  /v1/schedule:
    $ref: ./paths/schedule.yaml
  /v1/seasons:
    $ref: ./paths/season.yaml
  /v1/seasons/all:
    $ref: ./paths/allSeasons.yaml
  /v1/teams:
    $ref: ./paths/teams.yaml
  /v1/standings:
    $ref: ./paths/standings.yaml

components:
  parameters:
    $ref: ./components/parameters/parameters.yaml
  schemas:
    $ref: ./components/schemas/schemas.yaml